### ISSUE TITLE
[sat6_create_hosts : Obtain Satellite6 Location ID] 400 error

### ISSUE THREAD

**Issue by michaelsstuff** [ahuffman/sat6-create-hosts#6]
Hi,

following tested with commit 57a1b7c

Task "Obtain Satellite6 Location ID" stops with fatal:

```
"content": "{\"status\":400,\"error\":\"There was a problem in the JSON you submitted: 751: unexpected token at '{\\\"search\\\": 'name=\\\"Nürnberg\\\"'}'\"}",
```

I am not 100% sure what is happening, but are you sending a search data body?
I think Locations does not support this? https://theforeman.org/api/1.22/apidoc/v2/locations.html

The yaml files is this:
```
---
- name: "Satellite 6 create new hosts"
  hosts: "localhost"
  tasks:
    - name: "Provision Satellite 6 Hosts"
      include_role:
        name: "sat6_create_hosts"
      vars:
        sat6_fail_on_existing: False
        sat6_hosts:
          - name: "dev-app-1"
            domain: "mydomain.de"
            host_group: "Ansible/API"
            location: "Nürnberg"
            ipv4: "XXX.XXX.XXX.XXX"
            subnet: "255.255.255.128"
            compute_resource: "vcsa"
            compute_profile: "API APP"
            parameters:
              - name: "kt_activation_keys"
                value: "rhel7"
```
